<a href="https://colab.research.google.com/github/ogawa-tomohiro-1220/pytorch_udemy/blob/main/200409_pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch tutorial

## テンソルの生成

In [3]:
import torch

In [7]:
# テンソルを生成 5行３列のランダムな2次元行列
x = torch.empty(5,3)
print(x)

tensor([[1.8215e+20, 3.0782e-41, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [4.4721e+21, 1.5956e+25, 4.7399e+16],
        [3.7293e-08, 1.4838e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [11]:
# 値を初期化して行列作成　　　乱数を発生させて初期化
# 0~1のランダムな値を生成
x = torch.rand(5,3)
x

tensor([[0.4842, 0.5610, 0.4795],
        [0.4784, 0.6404, 0.8991],
        [0.1716, 0.6895, 0.7626],
        [0.1800, 0.5035, 0.0615],
        [0.4406, 0.9802, 0.1375]])

In [13]:
# 0で初期化
x = torch.zeros(5,3, dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [16]:
# 初期値（データ）を与えてtensorを生成
x =torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [18]:
# 1で初期化
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
# _likeで形状を継承
# randn: 平均が０、分散が１になるような乱数発生
x = torch.randn_like(x, dtype = torch.float)
x

tensor([[-0.2977, -0.2902, -1.3661],
        [ 0.1800, -0.5479,  0.6444],
        [-0.1645,  0.4044, -0.1516],
        [ 0.9799,  1.1567, -1.3930],
        [ 1.8504,  0.2420, -0.3307]])

In [22]:
x.size()

torch.Size([5, 3])

## テンソルの演算

In [24]:
y = torch.rand(5,3)
y

tensor([[0.4205, 0.4624, 0.8938],
        [0.7817, 0.1029, 0.9111],
        [0.4064, 0.9546, 0.9987],
        [0.8986, 0.5526, 0.9295],
        [0.8171, 0.6243, 0.5298]])

In [25]:
# 各要素の足し算
x + y

tensor([[ 0.1227,  0.1722, -0.4723],
        [ 0.9617, -0.4450,  1.5555],
        [ 0.2420,  1.3590,  0.8472],
        [ 1.8784,  1.7093, -0.4635],
        [ 2.6675,  0.8664,  0.1991]])

In [27]:
torch.add(x, y)

tensor([[ 0.1227,  0.1722, -0.4723],
        [ 0.9617, -0.4450,  1.5555],
        [ 0.2420,  1.3590,  0.8472],
        [ 1.8784,  1.7093, -0.4635],
        [ 2.6675,  0.8664,  0.1991]])

In [28]:
result  = torch.empty(5, 3)
result

tensor([[2.7011e+20, 3.0782e-41, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44],
        [1.4153e-43, 1.5274e-43, 1.5695e-43],
        [1.6255e-43, 1.6956e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [29]:
# resultの内容が上書き
torch.add(x, y, out = result)

tensor([[ 0.1227,  0.1722, -0.4723],
        [ 0.9617, -0.4450,  1.5555],
        [ 0.2420,  1.3590,  0.8472],
        [ 1.8784,  1.7093, -0.4635],
        [ 2.6675,  0.8664,  0.1991]])

In [30]:
y.add_(x)

tensor([[ 0.1227,  0.1722, -0.4723],
        [ 0.9617, -0.4450,  1.5555],
        [ 0.2420,  1.3590,  0.8472],
        [ 1.8784,  1.7093, -0.4635],
        [ 2.6675,  0.8664,  0.1991]])

In [31]:
x[:, 1]

tensor([-0.2902, -0.5479,  0.4044,  1.1567,  0.2420])

## NumPyとの連携

In [32]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [33]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [36]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [37]:
# aの要素を更新するとbも更新される！
b

array([2., 2., 2., 2., 2.], dtype=float32)

### NumPyからTorch Tensorへ

In [38]:
import numpy as np

In [41]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)

array([2., 2., 2., 2., 2.])

In [42]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)